export const enum ROLE {
  STUDENT = "STUDENT",
  MENTOR = "MENTOR",
  COLLEGE = "COLLEGE",
  EMPLOYER = "EMPLOYER",
  ADMIN = "ADMIN",
  SUPERADMIN = "SUPERADMIN",
  COUNSELOR = "COUNSELOR",
  EVENTMANAGER = "EVENTMANAGER",
  GOVEMPLOYER = "GOVEMPLOYER",
}
   